apiVersion: v1
kind: Service
metadata:
  name: gitops-app-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: gitops-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007

